name: Kernel BUILD
on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v2

    - name: Android kernel build
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        NAME: xiaomi-kernel
      with:
        arch: arm64
        compiler: proton-clang/master
        defconfig: joyeuse_defconfig
        image: Image

    - name: Upload artifacts
      uses: actions/upload-artifact@v2.2.4
      with:
        name: Kernel Image
        path: Image.gz
